import DashboardLayout from "@/components/DashboardLayout";
import { ConsoleHeader, StatusPill } from "@/components/foundry-ui";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, DatabaseBackup, HardDriveDownload, KeyRound, MonitorCheck, Plus, RotateCw, ShieldCheck, Trash2 } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const providers = [
  { value: "jules", label: "Jules API key", copy: "Creates and monitors asynchronous coding sessions." },
  { value: "gemini", label: "Gemini API key", copy: "Compiles natural language into typed task graphs." },
  { value: "github", label: "GitHub fine-grained token", copy: "Validates source repositories and target branches." },
] as const;

export default function Credentials() {
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<any>(null);
  const [provider, setProvider] = useState<"jules" | "gemini" | "github">("jules");
  const [label, setLabel] = useState("");
  const [secret, setSecret] = useState("");
  const [restoreCandidate, setRestoreCandidate] = useState<string | null>(null);
  const utils = trpc.useUtils();
  const profiles = trpc.foundry.credentials.list.useQuery();
  const localStatus = trpc.local.status.useQuery();
  const diagnostics = trpc.local.diagnostics.useQuery();
  const backups = trpc.local.listBackups.useQuery();
  const settings = trpc.local.settings.useQuery();
  const save = trpc.foundry.credentials.save.useMutation({ onSuccess: () => { toast.success(editing ? "Credential rotated" : "Credential saved", { description: "The raw secret is no longer available to the browser." }); utils.foundry.credentials.list.invalidate(); setOpen(false); setEditing(null); setLabel(""); setSecret(""); } });
  const test = trpc.foundry.credentials.test.useMutation({ onSuccess: result => { toast[result.ok ? "success" : "error"](result.ok ? "Connection verified" : "Credential test failed", { description: result.message }); utils.foundry.credentials.list.invalidate(); } });
  const remove = trpc.foundry.credentials.delete.useMutation({ onSuccess: () => { toast.success("Credential removed"); utils.foundry.credentials.list.invalidate(); } });
  const createBackup = trpc.local.createBackup.useMutation({ onSuccess: backup => { toast.success("Local backup created", { description: `${backup.filename} was created in your local Foundry backup directory.` }); backups.refetch(); }, onError: error => toast.error("Local backup failed", { description: error.message }) });
  const verifyBackup = trpc.local.verifyBackup.useMutation({ onSuccess: ok => toast[ok ? "success" : "error"](ok ? "Backup integrity verified" : "Backup integrity check failed") });
  const stageRestore = trpc.local.stageRestore.useMutation({ onSuccess: result => { toast.success("Restore staged safely", { description: result.message }); setRestoreCandidate(null); }, onError: error => toast.error("Restore staging failed", { description: error.message }) });
  const pruneBackups = trpc.local.pruneBackups.useMutation({ onSuccess: result => { toast.success("Backup retention applied", { description: `${result.removed.length} old backup(s) removed.` }); backups.refetch(); } });
  const updateSettings = trpc.local.updateSettings.useMutation({ onSuccess: () => settings.refetch() });
  const begin = (item?: any) => { setEditing(item ?? null); setProvider(item?.provider ?? "jules"); setLabel(item?.label ?? ""); setSecret(""); setOpen(true); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!secret.trim()) return toast.error("Enter the replacement secret before saving."); save.mutate({ provider, label, secret, credentialId: editing?.id }); };

  return <DashboardLayout>
    <ConsoleHeader eyebrow="Security / write-only provider keys" title="Credential vault" description="Provider credentials are encrypted server-side and write-only after submission. The console retains only a masked suffix, label, status, and test result." action={<Button onClick={() => begin()} className="bg-slate-950 text-white hover:bg-slate-800"><Plus className="mr-2 h-4 w-4" />Add credential</Button>} />
    <div className="mx-auto max-w-[1680px] space-y-6 p-5 sm:p-8 lg:p-10 2xl:p-12">
      <div className="grid gap-5 lg:grid-cols-3">
        {providers.map(item => {
          const profile = (profiles.data ?? []).find(candidate => candidate.provider === item.value);
          const health = profile?.status === "ready" ? "healthy" : profile?.status === "error" ? "attention" : "stale";
          return <div key={item.value} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_12px_35px_-25px_rgba(15,23,42,0.28)] lg:p-6">
            <div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-700"><KeyRound className="h-5 w-5" /></div>{profile ? <StatusPill value={health} /> : <span className="text-xs font-medium text-slate-400">Not configured</span>}</div>
            <h2 className="mt-5 text-sm font-semibold text-slate-950">{item.label}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{item.copy}</p>
            {profile ? <div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-medium text-slate-700">{profile.label} <span className="font-normal text-slate-400">{profile.maskedSecret}</span></p><p className="mt-1 text-[10px] text-slate-400">Version {profile.version} · {profile.lastTestedAt ? `tested ${new Date(profile.lastTestedAt).toLocaleDateString()}` : "not tested"}</p><div className="mt-4 flex gap-2"><Button onClick={() => test.mutate({ credentialId: profile.id })} disabled={test.isPending} size="sm" variant="outline" className="border-slate-300"><CheckCircle2 className="mr-1.5 h-3.5 w-3.5" />Test</Button><Button onClick={() => begin(profile)} size="sm" variant="ghost" className="text-cyan-700"><RotateCw className="mr-1.5 h-3.5 w-3.5" />Rotate</Button><Button onClick={() => remove.mutate({ credentialId: profile.id })} size="icon" variant="ghost" className="ml-auto text-rose-600"><Trash2 className="h-3.5 w-3.5" /></Button></div>{profile.lastError && <p className="mt-3 text-[10px] leading-4 text-rose-600">{profile.lastError}</p>}</div> : <Button onClick={() => begin()} variant="outline" className="mt-5 border-slate-300">Configure</Button>}
          </div>;
        })}
      </div>
      <div className="rounded-2xl border border-cyan-100 bg-cyan-50/50 p-5 lg:p-6"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-cyan-700" /><div><h3 className="text-sm font-semibold text-slate-900">Credential handling boundary</h3><p className="mt-1 text-sm leading-6 text-slate-600">Raw values travel from this form to the protected backend only. They are encrypted before persistence, omitted from all list/read procedures, excluded from mission events, and cannot be retrieved by this dashboard after the initial submission.</p></div></div></div>
      <div className="grid gap-5 xl:grid-cols-[1fr_auto] xl:items-center rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_12px_35px_-25px_rgba(15,23,42,0.28)] lg:p-6"><div className="flex gap-3"><MonitorCheck className="h-5 w-5 shrink-0 text-cyan-700" /><div><h3 className="text-sm font-semibold text-slate-900">Trusted-machine local runtime</h3><p className="mt-1 text-sm leading-6 text-slate-600">Foundry is listening only on this machine’s loopback interface. Its SQLite audit database and encrypted credential blobs are stored locally; Gemini, Jules, and GitHub remain the only intentional outbound provider calls.</p><p className="mt-2 text-[11px] font-medium text-slate-500">{diagnostics.data?.vault.available ? `${diagnostics.data.vault.mode === "os_keychain" ? "OS secure storage is protecting the local vault." : "Passphrase fallback is protecting the local vault."} ${localStatus.data?.monitoringRunsOnlyWhileApplicationIsRunning ? "Monitoring resumes checkpointed sessions while Foundry is running." : ""}` : diagnostics.data?.vault.message || "Checking local runtime status…"}</p></div></div><Button variant="outline" onClick={() => createBackup.mutate()} disabled={createBackup.isPending} className="border-slate-300"><DatabaseBackup className="mr-2 h-4 w-4" />{createBackup.isPending ? "Creating backup…" : "Create local backup"}</Button></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_12px_35px_-25px_rgba(15,23,42,0.28)] lg:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-sm font-semibold text-slate-900">Local recovery and retention</h3><p className="mt-1 text-sm leading-6 text-slate-600">Backups are local SQLite snapshots. A restore is staged into a separate directory and never overwrites the active ledger automatically.</p></div><div className="flex items-center gap-2"><Select value={String(settings.data?.backupRetention ?? 14)} onValueChange={value => updateSettings.mutate({ backupRetention: Number(value) })}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent>{[3, 7, 14, 30, 90].map(value => <SelectItem key={value} value={String(value)}>Keep {value}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={() => pruneBackups.mutate({ retain: settings.data?.backupRetention ?? 14 })} disabled={pruneBackups.isPending} className="border-slate-300">Apply retention</Button></div></div><div className="mt-5 divide-y divide-slate-100 rounded-xl border border-slate-100">{(backups.data ?? []).length ? backups.data!.map(backup => <div key={backup.filename} className="flex flex-wrap items-center gap-3 p-3 text-xs"><HardDriveDownload className="h-4 w-4 text-slate-400" /><div className="min-w-0 flex-1"><p className="truncate font-medium text-slate-700">{backup.filename}</p><p className="mt-1 text-slate-400">{new Date(backup.createdAt).toLocaleString()} · {(backup.sizeBytes / 1024 / 1024).toFixed(1)} MB</p></div><Button size="sm" variant="ghost" onClick={() => verifyBackup.mutate({ filename: backup.filename })}>Verify</Button><Button size="sm" variant="outline" className="border-slate-300" onClick={() => setRestoreCandidate(backup.filename)}>Stage restore</Button></div>) : <p className="p-4 text-sm text-slate-500">No local snapshots yet. Create a backup before major provider, task, or application changes.</p>}</div></div>
    </div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "Rotate credential" : "Add credential"}</DialogTitle><DialogDescription>{editing ? "Enter a replacement secret. The previous value is never shown or copied back to this interface." : "Credential values are treated as write-only and are never returned after saving."}</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label>Provider</Label><Select value={provider} onValueChange={value => setProvider(value as typeof provider)} disabled={Boolean(editing)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{providers.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="label">Label</Label><Input id="label" value={label} onChange={event => setLabel(event.target.value)} placeholder="Primary engineering account" required /></div><div className="space-y-2"><Label htmlFor="secret">{editing ? "Replacement secret" : "Secret"}</Label><Input id="secret" type="password" value={secret} onChange={event => setSecret(event.target.value)} placeholder="Paste a provider credential" autoComplete="off" required /></div><Button type="submit" className="w-full bg-slate-950 text-white hover:bg-slate-800" disabled={save.isPending}>{save.isPending ? "Sealing credential…" : editing ? "Rotate credential" : "Save credential"}</Button></form></DialogContent></Dialog>
    <Dialog open={Boolean(restoreCandidate)} onOpenChange={open => { if (!open && !stageRestore.isPending) setRestoreCandidate(null); }}><DialogContent><DialogHeader><DialogTitle>Stage verified restore</DialogTitle><DialogDescription>This copies and integrity-checks the selected local SQLite snapshot in a separate restore directory. It cannot overwrite the active ledger or restart any monitor.</DialogDescription></DialogHeader><div className="rounded-lg bg-slate-50 p-3 font-mono text-xs text-slate-600 break-all">{restoreCandidate}</div><p className="text-sm leading-6 text-slate-600">Review the staged copy after stopping Foundry before promoting it through your operating system. Continue only if this is the recovery point you intend to inspect.</p><div className="flex justify-end gap-3"><Button variant="outline" onClick={() => setRestoreCandidate(null)} disabled={stageRestore.isPending}>Cancel</Button><Button onClick={() => restoreCandidate && stageRestore.mutate({ filename: restoreCandidate })} disabled={!restoreCandidate || stageRestore.isPending} className="bg-slate-950 text-white hover:bg-slate-800">{stageRestore.isPending ? "Staging restore…" : "Stage verified restore"}</Button></div></DialogContent></Dialog>
  </DashboardLayout>;
}
