import DashboardLayout from "@/components/DashboardLayout";
import { ConsoleHeader, EmptyState, ProviderLink, ReconcileButton, StatusPill } from "@/components/foundry-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { AlertCircle, ChevronRight, Filter, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

export default function Fleet() {
  const [, setLocation] = useLocation();
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const fleet = trpc.foundry.observatory.fleet.useQuery(undefined, { refetchInterval: 30000 });
  const reconcile = trpc.foundry.observatory.reconcile.useMutation({ onSuccess: () => fleet.refetch() });
  const tasks = useMemo(() => (fleet.data ?? []).filter(task => (filter === "all" || task.health === filter) && `${task.title} ${task.repository} ${task.julesState}`.toLowerCase().includes(query.toLowerCase())), [fleet.data, filter, query]);
  const taskAge = (value: Date | string) => { const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 60 ? `${minutes}m` : minutes < 1440 ? `${Math.floor(minutes / 60)}h` : `${Math.floor(minutes / 1440)}d`; };

  return <DashboardLayout>
    <ConsoleHeader eyebrow="Observability / live mission registry" title="Fleet observatory" description="A read-through view of every dispatched Jules task. Health is derived from provider state, activity freshness, and monitoring evidence." action={<ReconcileButton onClick={() => reconcile.mutate()} loading={reconcile.isPending} />} />
    <div className="mx-auto min-w-0 max-w-[1600px] p-5 sm:p-8 lg:p-10">
      <div className="mb-5 flex min-w-0 flex-col justify-between gap-4 md:flex-row"><div className="relative min-w-0 max-w-md flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search title, repository, or state" className="h-10 border-slate-300 bg-white pl-9" /></div><div className="flex flex-wrap gap-2">{["all", "healthy", "stale", "attention", "terminal"].map(value => <Button key={value} onClick={() => setFilter(value)} variant={filter === value ? "default" : "outline"} className={filter === value ? "bg-slate-950 capitalize hover:bg-slate-800" : "border-slate-300 bg-white capitalize"}>{value}</Button>)}</div></div>
      {fleet.isLoading ? <div className="h-72 animate-pulse rounded-2xl bg-slate-200/70" /> : tasks.length === 0 ? <EmptyState title="Fleet is clear" description="No task matches this filter. Compile an initiative and dispatch a task to begin an observable Jules mission." action={<Button onClick={() => setLocation("/initiatives")}><Filter className="mr-2 h-4 w-4" />Open initiatives</Button>} /> : <>
        <div className="hidden min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_12px_35px_-25px_rgba(15,23,42,0.3)] 2xl:block"><div className="max-w-full overflow-x-auto overscroll-x-contain"><table className="w-full min-w-[1050px] text-left"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500"><tr><th className="px-5 py-3">Mission</th><th className="px-4 py-3">Health</th><th className="px-4 py-3">Provider state</th><th className="px-4 py-3">Risk</th><th className="px-4 py-3">Age</th><th className="px-4 py-3">Last poll</th><th className="px-4 py-3">Pull request</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{tasks.map(task => <tr key={task.id} className="group hover:bg-slate-50/70"><td className="px-5 py-4"><button onClick={() => setLocation(`/tasks/${task.id}`)} className="max-w-[300px] text-left"><p className="truncate text-sm font-semibold text-slate-900">{task.title}</p><p className="mt-1 truncate text-xs text-slate-500">{task.repository} · {task.branch}</p></button></td><td className="px-4 py-4"><StatusPill value={task.health} /></td><td className="px-4 py-4"><span className="text-xs font-medium text-slate-700">{task.julesState || "Not dispatched"}</span></td><td className="px-4 py-4"><StatusPill value={task.riskTier} kind="risk" /></td><td className="px-4 py-4"><span className="font-mono text-xs font-medium text-slate-600">{taskAge(task.createdAt)}</span></td><td className="px-4 py-4"><p className="text-xs text-slate-600">{task.lastPolledAt ? new Date(task.lastPolledAt).toLocaleString() : "Never"}</p>{task.lastError && <p className="mt-1 flex max-w-[220px] items-center gap-1 truncate text-[10px] text-rose-600"><AlertCircle className="h-3 w-3" />{task.lastError}</p>}</td><td className="px-4 py-4"><ProviderLink href={task.prUrl} label={task.prUrl ? "Open PR" : "No PR yet"} /></td><td className="px-4 py-4"><Button onClick={() => setLocation(`/tasks/${task.id}`)} size="icon" variant="ghost" className="rounded-full"><ChevronRight className="h-4 w-4" /></Button></td></tr>)}</tbody></table></div></div>
        <div className="grid min-w-0 gap-3 2xl:hidden md:grid-cols-2">{tasks.map(task => <button key={task.id} onClick={() => setLocation(`/tasks/${task.id}`)} className="w-full min-w-0 rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-[0_12px_35px_-25px_rgba(15,23,42,0.3)] transition hover:border-cyan-300"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{task.title}</p><p className="mt-1 truncate text-xs text-slate-500">{task.repository} · {task.branch}</p></div><ChevronRight className="mt-1 h-4 w-4 shrink-0 text-slate-400" /></div><div className="mt-4 flex flex-wrap gap-2"><StatusPill value={task.health} /><StatusPill value={task.riskTier} kind="risk" /><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-600">{task.julesState || "Not dispatched"}</span></div><div className="mt-3 flex items-center justify-between gap-3 border-t border-slate-100 pt-3 text-xs text-slate-500"><span>Age {taskAge(task.createdAt)}</span><span className="truncate text-right">{task.lastPolledAt ? `Polled ${new Date(task.lastPolledAt).toLocaleString()}` : "Not polled"}</span></div>{task.lastError && <p className="mt-3 flex items-start gap-1 text-xs text-rose-600"><AlertCircle className="mt-0.5 h-3 w-3 shrink-0" /><span className="line-clamp-2">{task.lastError}</span></p>}</button>)}</div>
      </>}
    </div>
  </DashboardLayout>;
}
