import DashboardLayout from "@/components/DashboardLayout";
import { ConsoleHeader, EmptyState, MetricCard, StatusPill } from "@/components/foundry-ui";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowRight, KeyRound, Network, Radar, Sparkles } from "lucide-react";
import { useEffect } from "react";
import { useLocation } from "wouter";

export default function Home() {
  const [, setLocation] = useLocation();
  const fleet = trpc.foundry.observatory.fleet.useQuery();
  const credentials = trpc.foundry.credentials.list.useQuery();
  const reconcile = trpc.foundry.observatory.reconcile.useMutation({ onSuccess: () => fleet.refetch() });
  useEffect(() => { reconcile.mutate(); }, []);
  const tasks = fleet.data ?? [];
  const health = (value: string) => tasks.filter(task => task.health === value).length;
  const readyCredentials = (credentials.data ?? []).filter(item => item.status === "ready").length;
  return <DashboardLayout><ConsoleHeader eyebrow="Jules orchestration / private control room" title="Command center" description="Compile intent into a governed task graph, dispatch to Jules, and preserve the evidence that makes every agent action explainable." action={<Button onClick={() => setLocation("/initiatives")} className="bg-slate-950 text-white hover:bg-slate-800"><Sparkles className="mr-2 h-4 w-4" />New initiative</Button>} />
    <div className="mx-auto min-w-0 max-w-[1680px] space-y-7 p-5 sm:p-8 lg:p-10 2xl:p-12"><section className="grid min-w-0 gap-4 md:grid-cols-2 lg:grid-cols-4"><MetricCard label="Active missions" value={tasks.filter(task => !["closed", "review_ready"].includes(task.state)).length} detail="Dispatched, gated, or executing" /><MetricCard label="Healthy sessions" value={health("healthy")} detail="Fresh monitor heartbeat" tone="cyan" /><MetricCard label="Needs attention" value={health("attention") + health("stale")} detail="Approval, feedback, or stale activity" tone="amber" /><MetricCard label="Vault readiness" value={`${readyCredentials}/3`} detail="Provider profiles verified" tone={readyCredentials === 3 ? "cyan" : "slate"} /></section>
      <section className="grid min-w-0 gap-6 lg:grid-cols-[minmax(0,1.55fr)_minmax(300px,0.95fr)]"><div className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_12px_35px_-25px_rgba(15,23,42,0.3)] lg:p-6"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Mission radar</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Recent task activity</h2></div><Button variant="ghost" onClick={() => setLocation("/fleet")} className="shrink-0 text-cyan-700">Open Fleet <ArrowRight className="ml-2 h-4 w-4" /></Button></div>{tasks.length === 0 ? <div className="mt-5"><EmptyState title="No missions in the ledger" description="Set up your provider credentials, then compile an initiative to create the first typed task graph." action={<Button onClick={() => setLocation("/credentials")} variant="outline"><KeyRound className="mr-2 h-4 w-4" />Open credential vault</Button>} /></div> : <div className="mt-5 divide-y divide-slate-100">{tasks.slice(0, 6).map(task => <button key={task.id} onClick={() => setLocation(`/tasks/${task.id}`)} className="grid w-full min-w-0 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 py-3 text-left"><div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-600"><Activity className="h-4 w-4" /></div><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-900">{task.title}</p><p className="mt-0.5 truncate text-xs text-slate-500">{task.repository} · {task.branch} · {task.julesState || "awaiting dispatch"}</p></div><StatusPill value={task.health} /></button>)}</div>}</div>
        <div className="rounded-2xl bg-[#111a31] p-5 text-white shadow-[0_18px_45px_-30px_rgba(15,23,42,0.7)]"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-300/70">Operator sequence</p><h2 className="mt-1 text-lg font-semibold">A bounded path to autonomous work.</h2><div className="mt-5 space-y-4">{[{ icon: KeyRound, title: "1. Seal the vault", copy: "Store write-only provider credentials." }, { icon: Network, title: "2. Compile intent", copy: "Generate a typed dependency DAG." }, { icon: Radar, title: "3. Observe evidence", copy: "Track activities, checks, and outcomes." }].map(step => <div className="flex gap-3" key={step.title}><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white/8 text-cyan-300"><step.icon className="h-4 w-4" /></div><div><p className="text-sm font-medium">{step.title}</p><p className="mt-0.5 text-xs leading-5 text-slate-400">{step.copy}</p></div></div>)}</div><Button onClick={() => setLocation(readyCredentials < 3 ? "/credentials" : "/initiatives")} className="mt-6 w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200">{readyCredentials < 3 ? "Configure providers" : "Create an initiative"}</Button></div></section>
    </div></DashboardLayout>;
}
