import DashboardLayout from "@/components/DashboardLayout";
import { ConsoleHeader, EmptyState, ProviderLink, StatusPill } from "@/components/foundry-ui";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { Activity, ArrowLeft, Check, CircleAlert, ClipboardCheck, Download, ExternalLink, FileCheck2, GitBranch, MessageSquare, Play, RefreshCw, Send, ShieldCheck, Timer, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

const sourceIcons: Record<string, any> = { local: Activity, jules: GitBranch, gemini: ClipboardCheck, github: ExternalLink };

export default function TaskDetail() {
  const [, params] = useRoute("/tasks/:id"); const [, setLocation] = useLocation(); const taskId = Number(params?.id); const [feedback, setFeedback] = useState(""); const [evidenceOpen, setEvidenceOpen] = useState(false); const [criterion, setCriterion] = useState(""); const [status, setStatus] = useState<"proven" | "partial" | "unproven" | "contradicted">("proven"); const [label, setLabel] = useState(""); const [reference, setReference] = useState(""); const [detail, setDetail] = useState("");
  const utils = trpc.useUtils(); const task = trpc.foundry.observatory.taskDetail.useQuery({ taskId }, { enabled: Boolean(taskId), refetchInterval: 30000 });
  const refresh = () => utils.foundry.observatory.taskDetail.invalidate({ taskId });
  const dispatch = trpc.foundry.dispatch.run.useMutation({ onSuccess: result => { toast.success(result.reused ? "Existing session reused" : "Jules session dispatched"); refresh(); }, onError: error => toast.error("Dispatch blocked", { description: error.message }) });
  const poll = trpc.foundry.observatory.poll.useMutation({ onSuccess: () => { toast.success("Mission refreshed"); refresh(); }, onError: error => toast.error("Polling failed", { description: error.message }) });
  const action = trpc.foundry.plans.action.useMutation({ onSuccess: () => { toast.success("Plan action recorded"); setFeedback(""); refresh(); }, onError: error => toast.error("Plan action failed", { description: error.message }) });
  const verify = trpc.foundry.evidence.verify.useMutation({ onSuccess: result => { toast.success(`Verification completed: ${result.verdict}`); refresh(); } });
  const addEvidence = trpc.foundry.evidence.add.useMutation({ onSuccess: () => { toast.success("Evidence linked to criterion"); setEvidenceOpen(false); setLabel(""); setReference(""); setDetail(""); refresh(); } });
  const dossier = trpc.foundry.evidence.dossier.useQuery({ taskId }, { enabled: false });
  const data: any = task.data; const eventTimeline = useMemo(() => data?.events?.slice().reverse() ?? [], [data?.events]);
  const submitEvidence = (event: FormEvent) => { event.preventDefault(); const active = data?.acceptanceCriteria?.find((item: any) => item.id === criterion); if (!active) return; addEvidence.mutate({ taskId, criterionId: active.id, criterionText: active.text, status, evidenceType: "verification", label, reference: reference || undefined, detail: detail || undefined }); };
  const exportDossier = async () => { const response = await dossier.refetch(); if (!response.data) return; const blob = new Blob([response.data.content], { type: "text/markdown" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = response.data.filename; link.click(); URL.revokeObjectURL(url); toast.success("Evidence dossier exported"); };
  if (task.isLoading) return <DashboardLayout><div className="h-screen animate-pulse bg-slate-100" /></DashboardLayout>;
  if (!data) return <DashboardLayout><ConsoleHeader eyebrow="Mission / unavailable" title="Task not found" description="The requested mission is not available in your workspace." /><div className="p-8"><EmptyState title="No mission record" description="Return to the Fleet observatory to select a task." action={<Button onClick={() => setLocation("/fleet")}>Return to Fleet</Button>} /></div></DashboardLayout>;
  const criterionRows = data.acceptanceCriteria.map((item: any) => ({ ...item, evidence: data.evidence.filter((evidence: any) => evidence.criterionId === item.id), status: data.evidence.find((evidence: any) => evidence.criterionId === item.id)?.status ?? "unproven" }));
  return <DashboardLayout><ConsoleHeader eyebrow={`Mission / ${data.taskKey}`} title={data.title} description={data.description} action={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setLocation("/fleet")} className="border-slate-300 bg-white"><ArrowLeft className="mr-2 h-4 w-4" />Fleet</Button><Button onClick={exportDossier} variant="outline" className="border-slate-300 bg-white"><Download className="mr-2 h-4 w-4" />Dossier</Button></div>} />
    <div className="mx-auto max-w-[1600px] space-y-6 p-5 sm:p-8 lg:p-10"><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Health</p><div className="mt-3"><StatusPill value={data.health} /></div><p className="mt-3 text-xs text-slate-500">{data.lastError || "Monitor has no active alert."}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Provider state</p><p className="mt-3 text-lg font-semibold text-slate-900">{data.julesState || "Not dispatched"}</p><p className="mt-3 text-xs text-slate-500">Last poll {data.lastPolledAt ? new Date(data.lastPolledAt).toLocaleString() : "not yet run"}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Scope</p><p className="mt-3 text-sm font-semibold text-slate-900">{data.repository}</p><p className="mt-1 text-xs text-slate-500">{data.branch} · {data.allowedPaths.length} allowed paths</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Budget ceiling</p><p className="mt-3 text-lg font-semibold text-slate-900">${(data.budgetCents / 100).toFixed(2)}</p><p className="mt-3 text-xs text-slate-500">{data.attempts.length} recorded attempts</p></div></section>
      <section className="grid gap-6 xl:grid-cols-[1.35fr_0.85fr]"><div className="space-y-6"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Mission controls</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Dispatch and intervention</h2></div><div className="flex flex-wrap gap-2">{!data.julesSessionName ? <Button onClick={() => dispatch.mutate({ taskId, requirePlanApproval: Boolean(data.requirePlanApproval), autoCreatePr: Boolean(data.autoCreatePr) })} disabled={dispatch.isPending} className="bg-slate-950 text-white hover:bg-slate-800"><Play className="mr-2 h-4 w-4" />Dispatch to Jules</Button> : <Button onClick={() => poll.mutate({ taskId })} disabled={poll.isPending} variant="outline" className="border-slate-300 bg-white"><RefreshCw className={cn("mr-2 h-4 w-4", poll.isPending && "animate-spin")} />Poll now</Button>}<Button onClick={() => verify.mutate({ taskId })} disabled={verify.isPending} variant="outline" className="border-slate-300 bg-white"><ShieldCheck className="mr-2 h-4 w-4" />Verify evidence</Button></div></div>
        <div className="mt-5 grid gap-3 rounded-xl bg-slate-50 p-4 text-xs text-slate-600 sm:grid-cols-3"><p><span className="font-semibold text-slate-900">Plan gate:</span> {data.requirePlanApproval ? "Human approval required" : "Auto-approved"}</p><p><span className="font-semibold text-slate-900">PR mode:</span> {data.autoCreatePr ? "AUTO_CREATE_PR" : "Manual"}</p><p><span className="font-semibold text-slate-900">Idempotency:</span> {data.idempotencyKey.slice(0, 20)}…</p></div></div>
        <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Mission timeline</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Append-only event ledger</h2></div><span className="text-xs text-slate-400">{eventTimeline.length} events</span></div><div className="mt-5 space-y-0">{eventTimeline.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Dispatch this task to begin its mission ledger.</p> : eventTimeline.map((event: any, index: number) => { const Icon = sourceIcons[event.source] || Activity; return <div key={event.id} className="relative flex gap-3 pb-5 last:pb-0"><div className="relative z-10 grid h-8 w-8 shrink-0 place-items-center rounded-full border border-slate-200 bg-white text-slate-500"><Icon className="h-3.5 w-3.5" /></div>{index < eventTimeline.length - 1 && <div className="absolute left-4 top-8 h-[calc(100%-20px)] w-px bg-slate-200" />}<div className="min-w-0 pt-1"><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><p className="text-sm font-medium text-slate-800">{event.summary}</p><span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">{event.source}</span></div><p className="mt-1 text-xs text-slate-400">{new Date(event.createdAt).toLocaleString()} · {event.eventType}</p></div></div> })}</div></div></div>
        <aside className="space-y-6"><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Plan gate</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Approval record</h2>{data.julesPlan ? <pre className="mt-4 max-h-52 overflow-auto rounded-xl bg-slate-950 p-3 font-mono text-[10px] leading-5 text-cyan-100">{JSON.stringify(data.julesPlan, null, 2)}</pre> : <p className="mt-3 text-sm leading-6 text-slate-500">The Jules-generated plan will appear here after the session reaches the plan gate.</p>}<Textarea value={feedback} onChange={event => setFeedback(event.target.value)} placeholder="Corrective guidance or rejection rationale" className="mt-4 min-h-20 border-slate-300 text-sm" /><div className="mt-3 grid grid-cols-3 gap-2"><Button onClick={() => action.mutate({ taskId, action: "approved" })} disabled={!data.julesSessionName || action.isPending} size="sm" className="bg-emerald-600 text-white hover:bg-emerald-700"><Check className="mr-1 h-3.5 w-3.5" />Approve</Button><Button onClick={() => action.mutate({ taskId, action: "corrective_message", message: feedback })} disabled={!data.julesSessionName || action.isPending} size="sm" variant="outline"><Send className="mr-1 h-3.5 w-3.5" />Guide</Button><Button onClick={() => action.mutate({ taskId, action: "rejected", message: feedback })} disabled={!data.julesSessionName || action.isPending} size="sm" variant="outline" className="text-rose-600"><X className="mr-1 h-3.5 w-3.5" />Reject</Button></div>{data.approvals.length > 0 && <div className="mt-4 border-t border-slate-100 pt-3">{data.approvals.slice(0, 3).map((item: any) => <p className="py-1 text-xs text-slate-500" key={item.id}><span className="font-medium text-slate-700">{item.action}</span> · {new Date(item.createdAt).toLocaleString()}</p>)}</div>}</div>
          <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Provider links</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Execution surfaces</h2></div><GitBranch className="h-5 w-5 text-slate-400" /></div><div className="mt-4 space-y-3"><ProviderLink href={data.julesSessionUrl} label="Open Jules session" /><ProviderLink href={data.prUrl} label="Open pull request" /></div><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs text-slate-500"><Timer className="mr-1 inline h-3.5 w-3.5" />Last activity {data.lastActivityAt ? new Date(data.lastActivityAt).toLocaleString() : "not yet recorded"}</p></div></div></aside></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5">
        <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center">
          <div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Operations ledger</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Attempts and cost boundary</h2></div>
          <p className="text-xs text-slate-500">Budget ceiling <span className="font-semibold text-slate-900">${(data.budgetCents / 100).toFixed(2)}</span> · Total API calls <span className="font-semibold text-slate-900">{data.attempts.reduce((sum: number, item: any) => sum + item.apiCallCount, 0)}</span></p>
        </div>
        <p className="mt-3 text-xs leading-5 text-slate-500">Spend is a conservative planning estimate of <span className="font-medium text-slate-700">$0.01 per recorded external provider call</span>; it is not provider-issued billing.</p>
        {data.attempts.length === 0 ? <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No dispatch, poll, approval, message, or verification attempt has been recorded yet.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="border-y border-slate-100 bg-slate-50 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500"><tr><th className="px-3 py-2">Attempt</th><th className="px-3 py-2">Outcome</th><th className="px-3 py-2">Created</th><th className="px-3 py-2">API calls</th><th className="px-3 py-2">Provider spend</th><th className="px-3 py-2">Elapsed</th><th className="px-3 py-2">Backoff / notes</th></tr></thead><tbody className="divide-y divide-slate-100">{data.attempts.map((attempt: any) => <tr key={attempt.id}><td className="px-3 py-3"><p className="font-mono text-xs font-medium text-slate-700">{attempt.attemptType}</p><p className="mt-1 max-w-36 truncate font-mono text-[9px] text-slate-400">{attempt.idempotencyKey}</p></td><td className="px-3 py-3"><span className={cn("rounded-full px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.1em]", attempt.outcome === "success" ? "bg-emerald-50 text-emerald-700" : attempt.outcome === "failure" ? "bg-rose-50 text-rose-700" : "bg-slate-100 text-slate-600")}>{attempt.outcome}</span></td><td className="px-3 py-3 text-xs text-slate-600">{new Date(attempt.createdAt).toLocaleString()}</td><td className="px-3 py-3 font-mono text-xs text-slate-600">{attempt.apiCallCount}</td><td className="px-3 py-3 text-xs text-slate-500">{attempt.estimatedSpendCents == null ? "Not reported" : `$${(attempt.estimatedSpendCents / 100).toFixed(2)}`}</td><td className="px-3 py-3 font-mono text-xs text-slate-600">{attempt.elapsedMs ? `${attempt.elapsedMs}ms` : "—"}</td><td className="px-3 py-3 text-xs text-slate-500">{attempt.backoffReason || "No backoff"}</td></tr>)}</tbody></table></div>}
        <div className="mt-6 border-t border-slate-100 pt-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Poll history</p><p className="mt-1 text-sm font-semibold text-slate-900">Idempotent monitor calls</p></div><span className="font-mono text-[10px] text-slate-400">30-second polling buckets</span></div><div className="mt-3 grid gap-3 md:grid-cols-3">{data.attempts.filter((attempt: any) => attempt.attemptType === "poll").length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 md:col-span-3">No poll attempts yet. The first reconciliation will write a monitor record here.</p> : data.attempts.filter((attempt: any) => attempt.attemptType === "poll").map((attempt: any) => <div key={attempt.id} className="rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="flex items-center justify-between"><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.1em] text-cyan-700">poll</span><span className="text-[10px] text-slate-400">{attempt.outcome}</span></div><p className="mt-2 text-xs font-medium text-slate-700">{new Date(attempt.createdAt).toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">{attempt.apiCallCount} API call{attempt.apiCallCount === 1 ? "" : "s"} · {attempt.elapsedMs ? `${attempt.elapsedMs}ms` : "pending"}</p><p className="mt-1 text-xs text-slate-500">Provider spend: {attempt.estimatedSpendCents == null ? "not reported" : `$${(attempt.estimatedSpendCents / 100).toFixed(2)}`}</p><p className="mt-2 truncate font-mono text-[9px] text-slate-400">{attempt.idempotencyKey}</p></div>)}</div></div>
      </section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Proof stack</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Evidence and verification</h2></div><Button onClick={() => { setCriterion(data.acceptanceCriteria[0]?.id ?? ""); setEvidenceOpen(true); }} variant="outline" className="border-slate-300 bg-white"><FileCheck2 className="mr-2 h-4 w-4" />Link evidence</Button></div><div className="mt-5 divide-y divide-slate-100">{criterionRows.map((item: any) => <div key={item.id} className="grid gap-3 py-4 md:grid-cols-[auto_1fr_auto]"><StatusPill value={item.status} kind="evidence" /><div><p className="text-sm font-medium text-slate-800">{item.id} · {item.text}</p><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1">{item.evidence.map((evidence: any) => <span key={evidence.id} className="text-xs text-slate-500">{evidence.label}{evidence.reference ? ` · ${evidence.reference}` : ""}</span>)}</div></div><span className="text-xs text-slate-400">{item.evidence.length} records</span></div>)}</div></section>
    </div><Dialog open={evidenceOpen} onOpenChange={setEvidenceOpen}><DialogContent><DialogHeader><DialogTitle>Link verification evidence</DialogTitle><DialogDescription>Evidence is appended to the task record and reflected in the exportable dossier.</DialogDescription></DialogHeader><form onSubmit={submitEvidence} className="space-y-4"><div className="space-y-2"><Label>Acceptance criterion</Label><Select value={criterion} onValueChange={setCriterion}><SelectTrigger><SelectValue placeholder="Select a criterion" /></SelectTrigger><SelectContent>{data.acceptanceCriteria.map((item: any) => <SelectItem key={item.id} value={item.id}>{item.id}: {item.text}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Evidence status</Label><Select value={status} onValueChange={value => setStatus(value as typeof status)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["proven", "partial", "unproven", "contradicted"].map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="evidence-label">Label</Label><Input id="evidence-label" value={label} onChange={event => setLabel(event.target.value)} placeholder="CI test output" required /></div></div><div className="space-y-2"><Label htmlFor="evidence-reference">Artifact or PR reference</Label><Input id="evidence-reference" value={reference} onChange={event => setReference(event.target.value)} placeholder="https://… or artifact ID" /></div><div className="space-y-2"><Label htmlFor="evidence-detail">Note</Label><Textarea id="evidence-detail" value={detail} onChange={event => setDetail(event.target.value)} placeholder="Explain why this record supports or challenges the criterion." /></div><Button type="submit" disabled={addEvidence.isPending} className="w-full bg-slate-950 text-white hover:bg-slate-800">Append evidence</Button></form></DialogContent></Dialog></DashboardLayout>;
}
